
# strategy
With_SEG: False

# Data
DATASET: 'cityscale'
MEAN: [123.675, 116.28, 103.53]
STD: [58.395, 57.12, 57.375]
IMAGE_SIZE: 2048
PATCH_SIZE: 512

# Model 
ENCODER:
  BACKBONE: 'SAM-vit-b'
  SAM_CKPT_PATH: './sam_ckpts/sam_vit_b_01ec64.pth'
  ENCODER_OUTPUT_DIM: 256
  VIT_PATCH_SIZE: 16

FEATURE_UPSAMPLER:
  UPSAMPLER_OUTPUT_DIM: 128

# Topo Decoder
TOPO_DECODER:
  HIDDEN_DIM: 384   # transformer层流传的张量的维度 = ENCODER_OUTPUT_DIM + UPSAMPLER_OUTPUT_DIM
  NUM_HEADS: 8
  DEPTH: 4  # 多少个transformer encoder/decoder层堆叠
  DIM_FFN: 512
  NUM_QUERIES: 10 # 最多可预测多少个邻接点
  ROI_SIZE: 32
  NUM_POINTS: 512
  

